apiVersion:  rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-manager
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces","pods","deployments",statefulsets"]
  verbs: ["get", "list", "watch", "create", "delete"]
