apiVersion:  rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-manager
rules:
- apiGroups: ["","apps"]
  resources: ["nodes", "namespaces","pods","deployments",statefulsets","services"]
  verbs: ["get", "list", "watch", "create", "delete","update","patch"]

